version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.8.1
    container_name: pulsar
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - "8080:8080"
      - "6650:6650"
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped