version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.8.1
    container_name: pulsar
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - "8080:8080"
      - "6650:6650"
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped

  jobmanager:
    build: .
    container_name: jobmanager
    volumes:
      - .:/opt/flink-nlp
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
