version: '3.9'
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.9.1
    container_name: pulsar
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - '8080:8080'
      - '6650:6650'
    command: ['bin/pulsar', 'standalone']
    restart: unless-stopped

  jobmanager:
    build: .
    container_name: jobmanager
    volumes:
      - ./job-nlp:/opt/job-nlp
    hostname: 'jobmanager'
    expose:
      - '6123'
    ports:
      - '8081:8081'
    command: jobmanager
    depends_on:
      - pulsar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - pulsar

  taskmanager:
    image: flink:1.13.3-scala_2.11
    expose:
      - '6121'
      - '6122'
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./job-nlp:/opt/job-nlp
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - jobmanager
      - pulsar

  sql-client:
    build: ./sql-client
    container_name: pulsar-sql-client
    depends_on:
      - pulsar
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
    volumes:
      - ./sql-client/client:/opt/sql-client/client
    links:
      - jobmanager
      - pulsar
