version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar-all:2.8.1
    container_name: pulsar
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - "8080:8080"
      - "6650:6650"
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped

  jobmanager:
    build: .
    image: pyflink/pyflink:1.13.1-scala_2.11
    container_name: jobmanager
    volumes:
      - ./job-nlp:/opt/job-nlp
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
      - pulsar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  
  taskmanager:
    image: pyflink/pyflink:1.13.1-scala_2.11
    container_name: taskmanager
    volumes:
      - ./job-nlp:/opt/job-nlp
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  sql-client:
    build: ./sql-client
    container_name: pulsar-sql-client
    depends_on:
      - pulsar
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
